CREATE TABLE cars (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_brand INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    year SMALLINT,
    price DECIMAL(15,2),
    image_url VARCHAR(255),
    description TEXT,
    specifications JSON,
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_brand) REFERENCES daftarBrands(id) ON DELETE RESTRICT ON UPDATE CASCADE
);