CREATE TABLE cars (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    approval_status ENUM('Pending', 'Reviewed', 'Approved', 'Rejected') NOT NULL DEFAULT 'PENDING',
    id_brand INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    year SMALLINT,
    price DECIMAL(15,2),
    km INT,
    engine_cc SMALLINT,
    fuel_type ENUM('Gasoline', 'Diesel', 'Hybrid', 'Electric', 'Pertalite', 'Pertamax', 'Pertamax Turbo', 'Dexlite'), 
    previous_owners TINYINT, 
    license_plate VARCHAR(20),                     
    tax_valid_until DATE,                           
    color VARCHAR(50),                              
    seat_count TINYINT,                             
    airbag_count TINYINT,                           
    is_accident_free ENUM('Yes', 'No', 'N/A') DEFAULT 'N/A',
    is_flood_free ENUM('Yes', 'No', 'N/A') DEFAULT 'N/A',   
    hot_deal_label VARCHAR(50),
    engine VARCHAR(100),                                   
    transmission VARCHAR(50),                               
    horsepower SMALLINT,                                    
    status ENUM('Available', 'Hold', 'Sold Out') DEFAULT 'Available',   
    image_url VARCHAR(255),
    description TEXT,
    specifications JSON,
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_brand) REFERENCES daftarBrands(id) ON DELETE RESTRICT ON UPDATE CASCADE
);